sudo: required
services:
  - docker

before_install:
  - docker build -t akkilp/docker-react -f Dockerfile.dev .

script:
  - docker run akkilp/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker" 
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-057912440277"
  bucket_path: "docker" #same as app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

